#!/bin/bash
 
 test -z $1  2> /dev/null
 
 if [ $? -eq 1 ]; then
 
         echo  "$1" | base64 -d
         echo 
 else
         read -p "INSERT: " INS
         echo  "$INS" | base64 -d
         echo 
 fi
